export const Permission = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  MANAGE_PRICING: "MANAGE_PRICING",
  MANAGE_METAL: "MANAGE_METAL",
  MANAGE_COEFFICIENTS: "MANAGE_COEFFICIENTS",
  MANAGE_TAX: "MANAGE_TAX",
  MANAGE_COMPANY: "MANAGE_COMPANY",
  MANAGE_NUMBERING: "MANAGE_NUMBERING",
  VIEW_INVOICES: "VIEW_INVOICES",
  CREATE_INVOICES: "CREATE_INVOICES",
  EDIT_INVOICES: "EDIT_INVOICES",
  DELETE_INVOICES: "DELETE_INVOICES",
  MANAGE_CLIENTS: "MANAGE_CLIENTS",
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_AUDIT: "VIEW_AUDIT",
  MANAGE_BACKUPS: "MANAGE_BACKUPS",
} as const;

export type PermissionName = typeof Permission[keyof typeof Permission];

export const Role = { ADMIN: "ADMIN", MANAGER: "MANAGER", VIEWER: "VIEWER" } as const;
export type RoleName = typeof Role[keyof typeof Role];
