import { Permission, Role, type PermissionName } from "@/lib/domain/access";
import type { AdminBootstrap, AdminData } from "@/lib/domain/admin-types";

const permissions = Object.values(Permission);
const permissionLabels = Object.fromEntries(permissions.map((permission) => [permission, permission])) as Record<PermissionName, string>;

export const e2eAdminBootstrap: AdminBootstrap = {
  user: {
    id: "e2e-admin",
    name: "Тестовый администратор",
    email: "admin@example.test",
    role: Role.ADMIN,
    permissions,
  },
  data: {
    dashboard: {
      today: { count: 2, total: 24_000 },
      month: { count: 18, total: 360_000 },
      year: { count: 140, total: 2_800_000 },
      all: { count: 240, total: 4_800_000, average: 20_000 },
      newClients: 4,
      months: [
        { key: "2026-07", label: "Июл", count: 12, total: 220_000 },
        { key: "2026-08", label: "Авг", count: 18, total: 360_000 },
      ],
      popularProducts: [{ name: "Воздуховод", quantity: 42, total: 180_000 }],
    },
    permissionLabels,
    products: [{
      id: "e2e-product",
      code: "duct",
      name: "Воздуховод",
      category: "Воздуховоды",
      active: true,
      formulaKey: "rectangular-duct",
      rates: [{
        id: "e2e-rate",
        productName: "Воздуховод",
        tierKey: "default",
        minBoundary: null,
        maxBoundary: null,
        thicknessCode: "0.5",
        materialMultiplier: 1,
        laborCost: 250,
        currentGrossRate: 732,
      }],
    }],
    thicknesses: [{ id: "e2e-thickness", code: "0.5", label: "0,5 мм", millimeters: 0.5, costPerSquareMeter: 350 }],
    coefficients: [{ id: "e2e-coefficient", key: "manufacturing", name: "Изготовление", value: 1, enabled: true }],
    tax: { enabled: true, rate: 22 },
    company: {
      name: "СБС",
      legalName: "ООО «ФЮСИС-В»",
      inn: "7707083893",
      kpp: "770701001",
      ogrn: "1027700132195",
      bankName: "Тестовый банк",
      bik: "044525225",
      checking: "40702810000000000000",
      correspondent: "30101810400000000225",
      address: "Москва, тестовый адрес",
      phone: "+7 000 000-00-00",
      email: "office@example.test",
      website: "sbs-schet.online",
      logoUrl: "/products/duct.png",
    },
    numbering: { pattern: "СБС-{NUMBER:5}", nextValue: 42, resetYearly: true },
    invoices: [{
      id: "e2e-invoice",
      number: "СБС-00041",
      status: "ISSUED",
      issueDate: "2026-08-20T12:00:00.000Z",
      client: "ООО «Тестовый клиент»",
      clientInn: "7707083893",
      total: 24_000,
      items: 1,
      manager: "Тестовый администратор",
    }, {
      id: "e2e-paid-invoice",
      number: "СБС-00040",
      status: "PAID",
      issueDate: "2026-08-19T12:00:00.000Z",
      client: "ООО «Оплативший клиент»",
      clientInn: "7707083894",
      total: 18_500,
      items: 2,
      manager: "Тестовый администратор",
    }],
    clients: [{
      id: "e2e-client",
      name: "ООО «Тестовый клиент»",
      inn: "7707083893",
      kpp: "770701001",
      address: "Москва",
      phone: "+7 000 000-00-00",
      email: "client@example.test",
      invoiceCount: 3,
      total: 72_000,
    }],
    users: [{
      id: "e2e-admin",
      name: "Тестовый администратор",
      email: "admin@example.test",
      role: Role.ADMIN,
      active: true,
      permissions,
    }],
    audit: [{
      id: "e2e-audit",
      createdAt: "2026-08-20T12:00:00.000Z",
      actor: "Тестовый администратор",
      action: "UPDATE",
      entityType: "ProductRate",
      entityId: "e2e-rate",
      before: { price: 700 },
      after: { price: 732 },
    }],
    backups: [{
      id: "e2e-backup",
      fileName: "sbs-e2e.sbsbak",
      size: 32_768,
      status: "READY",
      createdAt: "2026-08-20T12:00:00.000Z",
      createdBy: "Тестовый администратор",
    }],
  } satisfies AdminData,
};
